# Generated by Django 3.2.16 on 2022-11-16 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('enabled', models.BooleanField(default=False)),
                (
                    'key',
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='secret_token',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
